version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  initiator:
    build:
      context: .
      dockerfile: src/Initiator/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__ConnectionString=host=rabbitmq
      - QUEUE_NAME=Initiator_queue
      - CALCULATOR_URL=http://calculator:8080/calculator/receive
      - MESSAGE_TTL=8
      - NUMBER_OF_LAUNCHES=3
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
      - calculator

  calculator:
    build:
      context: .
      dockerfile: src/Calculator/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__ConnectionString=host=rabbitmq
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq
